#!/bin/bash

function deploy_single
{
    if [ -h ~/$2 ]
    then
        rm ~/$2
    fi
    ln -si $CWD/$1 ~/$2
}

function deploy_dir
{
    if [ -e $1/deploy ]
    then
        cd $1
	CWD=`pwd`
        . deploy
        CWD=`cd -`
    fi
}

function deploy_cache
{
    mkdir -p ~/.cache/$1
    touch ~/.cache/$1/$2
    if [ -e "~/.$2" ]
    then
        if [ ! -h "~/.$2" ]
        then
            mv ~/.{,cache/$1/}$2
        else
            warning "~/.$2 is symbolic link"
        fi
    fi
    ln -si ~/.cache/$1/$2 ~/.$2
}

function warning
{
    echo "[33m" "WARNING: " $* "[0m"
}
function error
{
    echo "[31m" "ERROR: " $* "[0m"
}

CWD=`pwd`

if [ $# -ge 1 ]
then
    for d in $*
    do
        deploy_dir $d
    done
else
    for d in `ls -d */`
    do
        deploy_dir $d
    done
fi
