
# Source ~/.bashrc for login shells as recommended by bash upstream
[[ -f ~/.bashrc ]] && source ~/.bashrc
[[ -f ~/.local/etc/bash_profile ]] && source ~/.local/etc/bash_profile

# Add the following to ~/.local/etc/bash_profile
#   tmux attach
